/**
 * YÖNETİCİ PANELİ METİNLERİ (Türkçe)
 * src/i18n altındaki mağaza sözlüğünden (S) bağımsızdır — panel kendi sözlüğünü kullanır.
 */

export const AS = {
  headerTitle: 'Teshvikiye — Yönetim',
  documentTitle: 'Yönetim — Teshvikiye',
  demoNotice: 'Demo — veriler yalnızca bu tarayıcıda saklanır',
  backToStore: 'Mağazaya dön',
  logout: 'Çıkış',
  skipToContent: 'İçeriğe geç',

  nav: {
    ariaLabel: 'Yönetim menüsü',
    dashboard: 'Gösterge',
    products: 'Ürünler',
    content: 'İçerik',
    settings: 'Ayarlar',
    orders: 'Siparişler',
    users: 'Kullanıcılar',
    data: 'Veri',
  },

  common: {
    yes: 'Evet',
    no: 'Hayır',
    loading: 'Yükleniyor…',
    retry: 'Tekrar dene',
  },

  /** API bağlı modda kullanılan ortak bildirimler (bkz. src/admin/adminApi.ts → useApiMode). */
  apiNotice: {
    saved: 'Kaydedildi.',
    saveError: 'Kaydedilemedi. Lütfen tekrar deneyin.',
    loadError: 'Veriler yüklenemedi.',
    ownerOnly: 'Bu işlem yalnızca hesap sahibi (owner) tarafından yapılabilir.',
    refresh: 'Yenile',
  },

  login: {
    title: 'Yönetici Girişi',
    usernameLabel: 'Kullanıcı adı',
    passwordLabel: 'Parola',
    submit: 'Giriş yap',
    error: 'Kullanıcı adı veya parola hatalı.',
    hint: 'Geçici giriş — backend bağlanınca veritabanı kullanıcılarına taşınacak.',
  },

  save: {
    save: 'Kaydet',
    saved: 'Kaydedildi — mağazada görmek için yenileyin',
    openStore: 'Mağazayı aç',
    reloadPage: 'Sayfayı yenile',
  },

  dashboard: {
    title: 'Gösterge',
    productsCard: 'Ürünler',
    visibleCount: (n: number) => `Görünen: ${n}`,
    hiddenCount: (n: number) => `Gizli: ${n}`,
    manageProducts: 'Ürünleri yönet',
    ordersCard: 'Demo siparişler',
    orderCount: (n: number) => `${n} sipariş`,
    viewOrders: 'Siparişleri görüntüle',
    missingMedia: 'Eksik marka görselleri',
    allMediaPresent: 'Tüm marka görselleri yüklü',
    manageMedia: 'Görselleri yönet',
    lastUpdate: 'Son güncelleme',
    neverUpdated: 'Henüz değişiklik yapılmadı',
    quickLinks: 'Hızlı bağlantılar',
    lowStockCard: 'Düşük stok',
    lowStockThreshold: (n: number) => `Eşik: 1–${n} adet`,
    lowStockCount: (n: number) => `Eşik altında: ${n} varyant`,
    outOfStockCount: (n: number) => `Tükenen: ${n} varyant`,
    lowStockNone: 'Eşik altında varyant yok.',
    lowStockRow: (number: string, color: string, size: string, qty: number) => `Ürün ${number} · ${color} / ${size} — ${qty} adet`,
    lowStockMore: (n: number) => `+${n} varyant daha`,
  },

  products: {
    title: 'Ürünler',
    searchLabel: 'Ara',
    searchPlaceholder: 'Ürün adı veya no',
    categoryLabel: 'Kategori',
    allCategories: 'Tüm kategoriler',
    empty: 'Aramanızla eşleşen ürün bulunamadı.',
    number: 'No',
    name: 'Ad',
    category: 'Kategori',
    price: 'Fiyat',
    stock: 'Toplam stok',
    isNew: 'Yeni',
    hidden: 'Gizli',
    hasImage: 'Görsel',
    edit: 'Düzenle',
    add: 'Yeni ürün ekle',
    addCategoryLabel: 'Kategori seçin',
    lowStock: 'Düşük stok',
    soldOut: 'Tükendi',
    lowStockTitle: (n: number, threshold: number) => `${n} varyant 1–${threshold} adet`,
    newAuto: 'Otomatik',
  },

  productEdit: {
    notFound: 'Ürün bulunamadı.',
    backToList: 'Listeye dön',
    title: (number: string) => `Ürün ${number} düzenle`,
    nameLabel: 'Ad',
    priceLabel: 'Fiyat',
    categoryLabel: 'Kategori',
    isNewLabel: 'Yeni ürün',
    newBadgeLabel: '"Yeni" rozeti',
    newBadgeOn: 'Manuel açık',
    newBadgeAuto: (days: number) => `Otomatik (${days} gün)`,
    newBadgeOff: 'Kapalı',
    newBadgeState: (active: boolean) => (active ? 'Mağazada şu an rozet görünüyor.' : 'Mağazada şu an rozet görünmüyor.'),
    stockHint: (threshold: number) =>
      `Her hücre 0–9999 arasında tam sayı. Vurgulu hücreler düşük stok (1–${threshold} adet); 0 = tükendi. Siparişler stoktan fazla oluşamaz.`,
    stockInvalid: 'Stok adetleri 0–9999 arasında tam sayı olmalı. Hatalı hücreleri düzeltin.',
    cellLow: 'düşük stok',
    cellOut: 'tükendi',
    hiddenLabel: 'Mağazada gizle',
    colorsTitle: 'Renkler',
    colorsHint: 'En az bir renk seçili olmalı.',
    stockTitle: 'Stok',
    contentTitle: 'İçerik',
    descriptionLabel: 'Açıklama',
    fabricCareLabel: 'Kumaş ve bakım',
    deliveryReturnsLabel: 'Teslimat ve iade',
    similarTitle: 'Benzer ürünler',
    completeLookTitle: 'Kombini tamamla',
    mediaTitle: 'Görseller',
    frontLabel: 'Ön görünüş',
    backLabel: 'Arka görünüş',
    modelLabel: 'Model üzerinde',
    fabricLabel: 'Kumaş detay',
    nameEnLabel: 'Ad — EN',
    descriptionEnLabel: 'Açıklama — EN',
    fabricCareEnLabel: 'Kumaş ve bakım — EN',
    colorLabelsEnTitle: 'Renk adları — EN',
    colorLabelEn: (label: string) => `${label} — EN`,
    enPlaceholder: 'Boşsa Türkçe gösterilir',
    enNote: '"EN" alanları İngilizce siteyi (/en) besler; boş bırakılırsa Türkçe metin gösterilir. Teslimat ve iade metninin EN karşılığı yoktur.',
    resetToDefault: 'Varsayılana dön',
    resetDone: 'Varsayılana döndürüldü — mağazada görmek için yenileyin',
  },

  content: {
    title: 'İçerik',
    brandTitle: 'Marka bilgileri',
    infoPagesTitle: 'Bilgi sayfaları',
    infoPagesSkipNote: '"İletişim" sayfası marka bilgileri alanlarını kullandığı için burada ayrıca listelenmez.',
    cookieTitle: 'Çerez metinleri',
    cookieBannerLabel: 'Banner metni',
    cookieCategoriesTitle: 'Çerez kategorisi açıklamaları',
    productionTitle: 'Üretim',
    productionIntroLabel: 'Giriş metni',
    productionStepsTitle: 'Aşamalar',
    sizeGuideTitle: 'Beden rehberi',
    enLabel: (label: string) => `${label} — EN`,
    enPlaceholder: 'Boşsa Türkçe gösterilir',
    enNote:
      'Her alanın altındaki "EN" alanı İngilizce siteyi (/en) besler. Hazır İngilizce metni olan alanlar dolu gelir; boş bırakılan alanda varsa hazır İngilizce metin, yoksa Türkçe metin gösterilir. Türkçe metni değiştirdiğinizde EN alanını da güncelleyin.',
  },

  settings: {
    title: 'Ayarlar',
    brandTitle: 'Marka',
    brandNameLabel: 'Marka adı',
    brandShortNameLabel: 'Kısa ad',
    discountTitle: '%10 kampanya',
    discountEnabledLabel: 'Kampanya aktif',
    discountPercentLabel: 'Yüzde',
    discountModeLabel: 'Uygulama şekli',
    discountModeAutomatic: 'Otomatik (hesap açınca)',
    discountModeCode: 'Kod ile',
    discountCodeLabel: 'İndirim kodu',
    discountMinSubtotalLabel: 'Minimum sepet tutarı (boş = tanımsız)',
    discountUsageLimitLabel: 'Kullanım sınırı (boş = tanımsız)',
    discountExpiresAtLabel: 'Son kullanım tarihi (boş = tanımsız)',
    discountFirstOrderOnlyLabel: 'Yalnızca ilk siparişte (iptal edilen sipariş sayılmaz)',
    shippingTitle: 'Kargo ücreti',
    shippingAmountLabel: 'Ücret (boş = tanımsız)',
    supportTitle: 'Destek',
    whatsappLabel: 'WhatsApp numarası (boş = tanımsız)',
    emailLabel: 'Destek e-postası (boş = tanımsız)',
    socialTitle: 'Sosyal bağlantılar',
    instagramLabel: 'Instagram (boş = tanımsız)',
    tiktokLabel: 'TikTok (boş = tanımsız)',
    pinterestLabel: 'Pinterest (boş = tanımsız)',
    offerTitle: 'Teklif paneli',
    offerDelayLabel: 'Çerez kararından sonraki gecikme (ms)',
    inventoryTitle: 'Stok ve "Yeni" rozeti',
    lowStockThresholdLabel: 'Düşük stok eşiği (adet)',
    newBadgeDaysLabel: 'Yeni rozeti gün sayısı',
    inventoryHint:
      'Stoğu 1 ile eşik arasında kalan varyantlar panelde "Düşük stok" olarak işaretlenir ve ürün sayfasında "Son N adet" notu çıkar. Otomatik rozetli ürünler oluşturulduktan sonra bu kadar gün "Yeni" görünür.',
    inventoryInvalid: 'Düşük stok eşiği 0–9999, gün sayısı 0–3650 arasında tam sayı olmalı.',
    mediaTitle: 'Marka görselleri',
    mediaLabels: {
      heroDesktop: 'Açılış görseli (masaüstü)',
      heroMobile: 'Açılış görseli (mobil)',
      collection: 'Koleksiyon tanıtım görseli',
      auth: 'Giriş / kayıt görseli',
      logo: 'Logo',
      productionVideo: 'Üretim videosu',
      productionVideoPoster: 'Üretim videosu kapak görseli',
      productionCutting: 'Kumaş kesim aşaması görseli',
      productionSewing: 'Dikim aşaması görseli',
      productionQuality: 'Kalite kontrol görseli',
    },
  },

  orders: {
    title: 'Siparişler',
    demoNotice: 'Demo sipariş — gerçek tahsilat yok',
    empty: 'Henüz demo sipariş oluşturulmadı.',
    no: 'No',
    date: 'Tarih',
    customer: 'Müşteri',
    itemCount: 'Ürün adedi',
    total: 'Genel toplam',
    items: 'Sipariş satırları',
    delivery: 'Teslimat adresi',
    totalsTitle: 'Tutarlar',
    subtotal: 'Ara toplam',
    discount: 'İndirim',
    shipping: 'Kargo',
    shippingUndefined: 'Tanımsız',
    grandTotal: 'Genel toplam',
    viewDetail: (id: string) => `${id} sipariş detayını görüntüle`,
  },

  data: {
    title: 'Veri',
    exportTitle: 'JSON olarak indir',
    exportHint: 'Tüm override verilerini ve yüklenen görselleri tek bir dosyada indirin.',
    exportButton: 'JSON olarak indir',
    importTitle: 'JSON yükle',
    importHint: 'Daha önce dışa aktarılmış bir dosyayı yükleyerek verileri geri getirin.',
    importSuccess: (mediaCount: number) => `İçe aktarıldı — ${mediaCount} görsel dahil.`,
    importError: (message: string) => `İçe aktarma başarısız: ${message}`,
    resetTitle: "Tüm override'ları sıfırla",
    resetHint: 'Tüm ürün, içerik ve ayar değişiklikleri ile yüklenen görseller kalıcı olarak silinir. Bu işlem geri alınamaz.',
    resetButton: "Tüm override'ları sıfırla",
    resetConfirmPrompt: 'Emin misiniz?',
    resetConfirmYes: 'Evet, sıfırla',
    resetConfirmNo: 'Vazgeç',
    resetDone: 'Sıfırlandı — mağazada görmek için yenileyin',
  },

  media: {
    upload: 'Yükle',
    replace: 'Değiştir',
    remove: 'Kaldır',
    largeFile: "Dosya 2 MB'tan büyük — yine de yüklenebilir.",
    removeUnavailable: 'Bu görsel için kaldırma API uç noktası henüz yok; yeni bir görsel yükleyerek değiştirebilirsiniz.',
  },

  /** API bağlı modda sipariş durumları (demo/new/paid/shipped/cancelled) — yerel demo durumlarından farklıdır. */
  ordersApi: {
    statusLabels: { demo: 'Demo', new: 'Yeni', paid: 'Ödendi', shipped: 'Kargoda', cancelled: 'İptal' } as Record<string, string>,
    statusLabel: 'Durum',
    changeStatus: 'Durumu güncelle',
    statusUpdated: 'Sipariş durumu güncellendi.',
    missingFeatures: 'İade/iptal/değişim talep akışı ve kargo takip numarası için API uç noktası henüz yok.',
  },

  /** `/admin/kullanicilar` — yalnızca API modunda gösterilir (GET/POST/PATCH /admin/users). */
  users: {
    title: 'Kullanıcılar',
    empty: 'Henüz yönetici kullanıcı yok.',
    username: 'Kullanıcı adı',
    role: 'Rol',
    roleOwner: 'Sahip (owner)',
    roleEditor: 'Editör',
    active: 'Aktif',
    inactive: 'Pasif',
    lastLogin: 'Son giriş',
    never: 'Hiç',
    createTitle: 'Yeni kullanıcı ekle',
    usernameLabel: 'Kullanıcı adı',
    passwordLabel: 'Parola',
    roleLabel: 'Rol',
    createButton: 'Kullanıcı ekle',
    created: 'Kullanıcı oluşturuldu.',
    changePasswordTitle: 'Parolayı değiştir',
    newPasswordLabel: 'Yeni parola',
    changePasswordButton: 'Parolayı güncelle',
    passwordChanged: 'Parola güncellendi.',
    deactivate: 'Pasifleştir',
    activate: 'Etkinleştir',
    ownerOnlyNote: 'Kullanıcı ekleme/düzenleme işlemleri yalnızca hesap sahibi (owner) tarafından yapılabilir.',
  },
} as const
