/**
 * YÖNETİCİ PANELİ METİNLERİ (yalnızca Türkçe)
 * src/i18n altındaki mağaza sözlüğünden (S) bağımsızdır — panel kendi sözlüğünü kullanır.
 */

const tl = (n: number) => `${n.toLocaleString('tr-TR')}`

export const AS = {
  headerTitle: 'Teshvikiye',
  headerSub: 'Yönetim',
  documentTitle: 'Yönetim — Teshvikiye',
  demoNotice: 'Demo — veriler yalnızca bu tarayıcıda saklanır',
  demoBadge: 'Yerel demo',
  backToStore: 'Mağazaya dön',
  logout: 'Çıkış',
  skipToContent: 'İçeriğe geç',

  nav: {
    ariaLabel: 'Yönetim menüsü',
    dashboard: 'Gösterge',
    analytics: 'Analitik',
    orders: 'Siparişler',
    products: 'Ürünler',
    coupons: 'Kuponlar',
    customers: 'Müşteriler',
    content: 'İçerik',
    media: 'Görseller',
    settings: 'Ayarlar',
    users: 'Kullanıcılar',
    data: 'Veri',
    groupSales: 'Satış',
    groupCatalog: 'Katalog',
    groupSystem: 'Sistem',
    collapse: 'Menüyü daralt',
    expand: 'Menüyü genişlet',
    open: 'Menüyü aç',
    close: 'Menüyü kapat',
    roleOwner: 'Sahip',
    roleEditor: 'Editör',
    roleLocal: 'Yerel oturum',
  },

  common: {
    yes: 'Evet',
    no: 'Hayır',
    loading: 'Yükleniyor…',
    retry: 'Tekrar dene',
    all: 'Tümü',
    none: '—',
    edit: 'Düzenle',
    delete: 'Sil',
    add: 'Ekle',
    view: 'Görüntüle',
    refresh: 'Yenile',
    unlimited: 'Sınırsız',
  },

  ui: {
    close: 'Kapat',
    cancel: 'Vazgeç',
    confirm: 'Onayla',
    search: 'Ara',
    clearFilters: 'Filtreleri temizle',
    notifications: 'Bildirimler',
    unavailableTitle: 'Sunucu güncellemesi bekleniyor',
    unavailableText: (feature: string) => `${feature} için gereken sunucu uç noktası henüz yayında değil. Sunucu güncellendiğinde bu sayfa kendiliğinden çalışır.`,
    loadErrorTitle: 'Veriler yüklenemedi',
    localOnlyTitle: 'Yalnızca sunucu bağlantısıyla',
    localOnlyText: (feature: string) => `${feature} yerel demo modunda kullanılamaz; sunucuya bağlı panelde çalışır.`,
    leaveTitle: 'Kaydedilmemiş değişiklikler var',
    leaveText: 'Bu sayfadan ayrılırsanız yaptığınız değişiklikler kaybolacak.',
    leaveConfirm: 'Değişiklikleri at ve çık',
    leaveCancel: 'Sayfada kal',
    sessionChecking: 'Oturum doğrulanıyor…',
  },

  table: {
    empty: 'Kayıt yok.',
    actions: 'Eylemler',
    selectPage: 'Bu sayfadaki tüm satırları seç',
    selectRow: (label: string) => `${label} seç`,
    selected: (n: number) => `${n} seçili`,
    clearSelection: 'Seçimi kaldır',
    bulkRegion: 'Toplu işlemler',
    pagination: 'Sayfalama',
    prev: 'Önceki sayfa',
    next: 'Sonraki sayfa',
    pageOf: (p: number, total: number) => `${p} / ${total}`,
    range: (from: number, to: number, total: number) => `${tl(from)}–${tl(to)} / ${tl(total)} kayıt`,
    count: (n: number) => `${tl(n)} kayıt`,
  },

  apiNotice: {
    saved: 'Kaydedildi.',
    saveError: 'Kaydedilemedi. Lütfen tekrar deneyin.',
    loadError: 'Veriler yüklenemedi.',
    ownerOnly: 'Bu işlem yalnızca hesap sahibi (owner) tarafından yapılabilir.',
    refresh: 'Yenile',
    validation: 'Bazı alanlar geçersiz. İşaretli alanları düzeltin.',
  },

  login: {
    title: 'Yönetici girişi',
    subtitle: 'Teshvikiye yönetim paneline giriş yapın.',
    usernameLabel: 'Kullanıcı adı',
    passwordLabel: 'Parola',
    submit: 'Giriş yap',
    error: 'Kullanıcı adı veya parola hatalı.',
    showPassword: 'Parolayı göster',
    hidePassword: 'Parolayı gizle',
  },

  save: {
    save: 'Kaydet',
    discard: 'Vazgeç',
    region: 'Kaydedilmemiş değişiklikler',
    unsaved: 'Kaydedilmemiş değişiklikler var',
    unsavedCount: (n: number) => `${n} alanda kaydedilmemiş değişiklik`,
    saved: 'Kaydedildi.',
    savedLocal: 'Kaydedildi — mağazada görmek için sayfayı yenileyin.',
    discarded: 'Değişiklikler geri alındı.',
    nothing: 'Değişiklik yok.',
    openStore: 'Mağazayı aç',
    reloadPage: 'Sayfayı yenile',
  },

  dashboard: {
    title: 'Gösterge',
    greeting: (name: string | null) => (name ? `Hoş geldiniz, ${name}` : 'Hoş geldiniz'),
    subtitle: 'Mağazanın bugünkü durumu ve dikkat gerektiren işler.',
    today: 'Bugün',
    week: 'Bu hafta',
    month: 'Bu ay',
    ordersSub: (n: number) => `${tl(n)} sipariş`,
    pendingPayment: 'Ödeme bekleyen',
    pendingPaymentSub: 'sipariş',
    lowStock: 'Düşük stok',
    lowStockSub: (threshold: number) => `varyant · eşik 1–${threshold}`,
    lowStockSubPlain: 'varyant',
    visits7d: 'Ziyaret (7 gün)',
    visits7dSub: (n: number) => `${tl(n)} sayfa görüntüleme`,
    recentOrders: 'Son siparişler',
    allOrders: 'Tüm siparişler',
    noOrders: 'Henüz sipariş yok.',
    lowStockTitle: 'Düşük stok',
    lowStockEmpty: 'Eşik altında varyant yok.',
    lowStockMore: (n: number) => `+${n} varyant daha`,
    lowStockRow: (color: string, size: string) => `${color} · ${size}`,
    qty: (n: number) => `${n} adet`,
    quickActions: 'Hızlı eylemler',
    newProduct: 'Yeni ürün',
    newCoupon: 'Yeni kupon',
    viewOrders: 'Siparişler',
    catalogTitle: 'Katalog',
    visibleCount: (n: number) => `${n} görünür ürün`,
    hiddenCount: (n: number) => `${n} gizli`,
    missingMedia: 'Eksik marka görselleri',
    allMediaPresent: 'Tüm marka görselleri yüklü.',
    manageMedia: 'Görselleri yönet',
    computedNote: 'Özet, sipariş listesinden hesaplandı (sunucu istatistik uç noktası henüz yok). Ciroya yeni, ödendi ve kargoda siparişler dahildir.',
    demoOrdersNote: 'Yerel demo siparişlerden hesaplandı.',
    lastUpdate: 'Son yerel değişiklik',
    neverUpdated: 'Henüz değişiklik yapılmadı',
  },

  products: {
    title: 'Ürünler',
    subtitle: 'Fiyat, stok, görünürlük ve rozetleri buradan yönetin. Fiyata tıklayıp Enter ile hızlıca değiştirebilirsiniz.',
    searchPlaceholder: 'Ürün adı',
    categoryLabel: 'Kategori',
    stockLabel: 'Stok durumu',
    stockAll: 'Tümü',
    stockOk: 'Stokta',
    stockLow: 'Düşük stok',
    stockOut: 'Tükendi',
    visibilityLabel: 'Görünürlük',
    visibilityVisible: 'Görünür',
    visibilityHidden: 'Gizli',
    empty: 'Aramanızla eşleşen ürün yok.',
    emptyAll: 'Henüz ürün yok.',
    colProduct: 'Ürün',
    colCategory: 'Kategori',
    colPrice: 'Fiyat',
    colStock: 'Stok',
    colBadge: '"Yeni" rozeti',
    colStatus: 'Durum',
    edit: 'Düzenle',
    editAria: (name: string) => `${name} düzenle`,
    add: 'Yeni ürün',
    addTitle: 'Yeni ürün',
    addText: 'Ürün mağazada gizli olarak oluşturulur; bilgilerini ve görsellerini tamamladıktan sonra görünür yapabilirsiniz.',
    addCategory: 'Kategori',
    addName: 'Ürün adı',
    addPrice: 'Fiyat (TL)',
    addSubmit: 'Oluştur ve düzenle',
    created: 'Ürün gizli olarak oluşturuldu; stok girip görünür yapmayı unutmayın.',
    lowStock: 'Düşük stok',
    soldOut: 'Tükendi',
    lowStockTitle: (n: number, threshold: number) => `${n} varyant 1–${threshold} adet`,
    badgeOn: 'Manuel',
    badgeAuto: 'Otomatik',
    badgeAutoActive: 'Otomatik · görünüyor',
    badgeOff: 'Kapalı',
    visible: 'Görünür',
    hidden: 'Gizli',
    noImage: 'Görsel yok',
    bulkHide: 'Gizle',
    bulkShow: 'Göster',
    bulkDone: (n: number, hidden: boolean) => `${n} ürün ${hidden ? 'gizlendi' : 'mağazada gösteriliyor'}.`,
    bulkPartial: (ok: number, fail: number) => `${ok} ürün güncellendi, ${fail} ürün güncellenemedi.`,
    priceAria: (name: string) => `${name} fiyatı — düzenlemek için tıklayın`,
    priceInputAria: (name: string) => `${name} yeni fiyat (Enter kaydeder, Esc vazgeçer)`,
    priceSaved: (name: string, price: string) => `${name}: fiyat ${price} olarak kaydedildi.`,
    priceInvalid: 'Fiyat 0 veya daha büyük bir sayı olmalı.',
    localOnlyActions: 'Yerel demo modunda satır içi fiyat ve toplu gizle/göster kapalıdır; ürünü açıp düzenleyin.',
    deleteAria: (name: string) => `${name} ürününü sil`,
    bulkDelete: 'Sil',
    deleteTitle: (n: number) => (n === 1 ? 'Ürün silinsin mi?' : `${n} ürün silinsin mi?`),
    deleteText: 'Bu işlem geri alınamaz. Ürün mağazadan ve panelden kalıcı olarak kaldırılır; geçmiş siparişlerdeki kalemler korunur.',
    deleteConfirm: 'Evet, sil',
    deleted: (name: string) => `${name} silindi.`,
    bulkDeleted: (n: number) => `${n} ürün silindi.`,
    bulkDeletePartial: (ok: number, fail: number) => `${ok} ürün silindi, ${fail} ürün silinemedi.`,
  },

  productEdit: {
    notFound: 'Ürün bulunamadı.',
    backToList: 'Ürünler',
    untitled: 'Adsız ürün',
    tabsLabel: 'Ürün bölümleri',
    tabGeneral: 'Genel',
    tabPricing: 'Fiyat ve stok',
    tabMedia: 'Görseller',
    tabEnglish: 'İngilizce',
    tabRelated: 'İlişkili ürünler',
    tabHasChanges: 'kaydedilmemiş değişiklik var',
    basicsTitle: 'Temel bilgiler',
    nameLabel: 'Ürün adı',
    nameRequired: 'Ürün adı boş olamaz.',
    nameTooLong: 'Ürün adı en fazla 200 karakter olabilir.',
    categoryLabel: 'Kategori',
    visibilityTitle: 'Görünürlük ve rozet',
    hiddenLabel: 'Mağazada gizle',
    hiddenHint: 'Gizli ürünler mağazada listelenmez ve ürün sayfası açılmaz.',
    isNewLabel: '"Yeni" rozeti',
    newBadgeLabel: '"Yeni" rozeti',
    newBadgeOn: 'Manuel açık',
    newBadgeAuto: (days: number) => `Otomatik (${days} gün)`,
    newBadgeOff: 'Kapalı',
    newBadgeState: (active: boolean) => (active ? 'Mağazada şu an rozet görünüyor.' : 'Mağazada şu an rozet görünmüyor.'),
    contentTitle: 'Ürün metinleri',
    descriptionLabel: 'Açıklama',
    fabricCareLabel: 'Kumaş ve bakım',
    deliveryReturnsLabel: 'Teslimat ve iade',
    deliveryReturnsHint: 'Teslimat ve iade metninin İngilizce karşılığı yoktur.',
    priceTitle: 'Fiyat',
    priceLabel: 'Satış fiyatı',
    priceInvalid: 'Fiyat 0 veya daha büyük bir sayı olmalı (ör. 1499,90).',
    priceZeroTitle: 'Fiyat 0 TL olacak',
    priceZeroText: 'Ürün mağazada ücretsiz görünecek. Bu fiyatla kaydetmek istediğinize emin misiniz?',
    priceZeroConfirm: 'Evet, 0 TL ile kaydet',
    colorsTitle: 'Renkler',
    colorsHint: 'En az bir renk seçili olmalı. Renk adını buradan değiştirebilirsiniz.',
    colorsHintApi: (max: number) => `En az bir renk olmalı, en fazla ${max} renk eklenebilir. Renk adları mağazadaki renk seçicide görünür.`,
    colorNameLabel: (id: string) => `${id} adı`,
    colorLabelRequired: 'Renk adı boş olamaz.',
    colorAdd: 'Renk ekle',
    colorAddMax: (max: number) => `En fazla ${max} renk eklenebilir.`,
    colorDefaultLabel: (n: number) => `Renk ${n}`,
    colorRemove: 'Kaldır',
    colorRemoveAria: (label: string) => `${label} rengini kaldır`,
    colorRemoveLastHint: 'Son renk kaldırılamaz.',
    colorRemoveTitle: (label: string) => `${label} rengi kaldırılsın mı?`,
    colorRemoveText: (total: number) => `Bu rengin ${total} adetlik stok kayıtları silinecek. Kaydettiğinizde bu renk mağazada seçilemez olur.`,
    colorRemoveConfirm: 'Rengi kaldır',
    stockTitle: 'Stok',
    stockHint: (threshold: number) => `Her hücre 0–9999 arası tam sayı. Sarı hücreler düşük stok (1–${threshold}), gri hücreler tükendi.`,
    stockInvalid: 'Stok adetleri 0–9999 arasında tam sayı olmalı. İşaretli hücreleri düzeltin.',
    fillAllLabel: 'Tüm hücrelere',
    fillAll: 'Doldur',
    copyRow: 'Diğer renklere kopyala',
    copyRowAria: (color: string) => `${color} satırını diğer renklere kopyala`,
    copyColumn: 'Aşağı kopyala',
    copyColumnAria: (size: string) => `${size} sütununda ilk satırın değerini tüm renklere kopyala`,
    rowTotal: 'Toplam',
    cellLow: 'düşük stok',
    cellOut: 'tükendi',
    mediaTitle: 'Ürün görselleri',
    mediaHint: 'Görseli sürükleyip bırakın ya da tıklayıp seçin. JPG, PNG, WebP veya AVIF; en fazla 15 MB. SVG kabul edilmez.',
    mediaRemoveUnsupported: 'Görsel kaldırılamadı — sunucu güncellemesi bekleniyor. Yeni bir görsel yükleyerek değiştirebilirsiniz.',
    mediaSaved: 'Görsel kaydedildi.',
    mediaDefault: 'Varsayılan dosya',
    mediaUploadedBadge: 'Yüklenen',
    mediaDefaultBadge: 'Varsayılan (sitede görünen)',
    mediaRemoved: 'Görsel kaldırıldı.',
    frontLabel: 'Ön görünüş',
    backLabel: 'Arka görünüş',
    modelLabel: 'Model üzerinde',
    fabricLabel: 'Kumaş detay',
    englishTitle: 'İngilizce site (/en)',
    englishHint: 'Boş bırakılan alanlarda İngilizce sitede Türkçe metin gösterilir.',
    nameEnLabel: 'Ürün adı — EN',
    descriptionEnLabel: 'Açıklama — EN',
    fabricCareEnLabel: 'Kumaş ve bakım — EN',
    colorLabelsEnTitle: 'Renk adları — EN',
    colorLabelEn: (label: string) => `${label} — EN`,
    enPlaceholder: 'Boşsa Türkçe gösterilir',
    similarTitle: 'Benzer ürünler',
    similarHint: 'Ürün sayfasındaki "Benzer ürünler" alanında gösterilir.',
    completeLookTitle: 'Kombini tamamla',
    completeLookHint: 'Ürün sayfasındaki "Kombini tamamla" alanında gösterilir.',
    relatedFilter: 'Ürün ara',
    selectedCount: (n: number) => `${n} seçili`,
    relatedNote: 'Gizli ya da stoğu tükenmiş ürünler mağazada gösterilmez. Seçim sırası mağazadaki gösterim sırasıdır.',
    relatedHidden: 'Gizli',
    relatedSoldOut: 'Stokta yok',
    relatedMoveUp: (name: string) => `${name} — yukarı taşı`,
    relatedMoveDown: (name: string) => `${name} — aşağı taşı`,
    relatedSelectedGroup: 'Seçili ürünler',
    relatedOthersGroup: 'Diğer ürünler',
    relatedNoMatch: 'Aramanızla eşleşen ürün yok.',
    resetToDefault: 'Varsayılana dön',
    resetConfirmTitle: 'Varsayılana dönülsün mü?',
    resetConfirmText: 'Bu ürün için yerelde yapılan tüm değişiklikler silinir.',
    resetDone: 'Varsayılana döndürüldü — mağazada görmek için yenileyin.',
    conflictTitle: 'Bu ürün başka bir yerde değiştirildi',
    conflictText: 'Siz düzenlerken ürün başka bir sekmede ya da başka bir yönetici tarafından kaydedildi. Üzerine yazmamak için kaydetme yapılmadı. Sayfayı yenileyip değişikliklerinizi yeniden uygulayın.',
    conflictReload: 'Yenile',
    viewInStore: 'Mağazada görüntüle',
    hiddenBadge: 'Gizli',
    visibleBadge: 'Görünür',
    dangerTitle: 'Tehlikeli bölge',
    dangerDesc: 'Ürünü kalıcı olarak silmek yerine mağazada gizlemeyi tercih edebilirsiniz.',
    deleteButton: 'Ürünü sil',
    deleteOwnerOnly: 'Ürünü yalnızca hesap sahibi (owner) silebilir; editör ürünü gizleyebilir.',
    deleteTitle: (name: string) => `"${name}" silinsin mi?`,
    deleteText: 'Bu işlem geri alınamaz. Ürün mağazadan ve panelden kalıcı olarak kaldırılır; geçmiş siparişlerdeki kalemler korunur.',
    deleteConfirm: 'Evet, ürünü sil',
    deleted: (name: string) => `"${name}" silindi.`,
    deletedWithOrders: (name: string, n: number) => `"${name}" silindi. ${n} geçmiş sipariş kalemi korundu.`,
  },

  orders: {
    title: 'Siparişler',
    subtitle: 'Siparişleri arayın, durumlarını güncelleyin, kargo bilgisini girin.',
    demoNotice: 'Demo sipariş — gerçek tahsilat yok',
    empty: 'Henüz sipariş yok.',
    emptyFiltered: 'Filtrelerle eşleşen sipariş yok.',
    searchPlaceholder: 'Sipariş no, e-posta veya ad',
    statusFilter: 'Durum',
    fromLabel: 'Başlangıç',
    toLabel: 'Bitiş',
    no: 'Sipariş',
    date: 'Tarih',
    customer: 'Müşteri',
    itemCount: 'Ürün',
    total: 'Tutar',
    items: 'Ürünler',
    itemsCount: (n: number) => `${n} ürün`,
    delivery: 'Teslimat',
    contact: 'İletişim',
    totalsTitle: 'Tutarlar',
    subtotal: 'Ara toplam',
    discount: 'İndirim',
    shipping: 'Kargo',
    shippingUndefined: 'Tanımsız',
    grandTotal: 'Genel toplam',
    viewDetail: (id: string) => `${id} sipariş detayını aç`,
    unitPrice: (qty: number, price: string) => `${qty} × ${price}`,
    timeline: 'Zaman çizelgesi',
    tlCreated: 'Sipariş oluşturuldu',
    tlPaymentStarted: 'Ödeme başlatıldı',
    tlPaid: 'Ödeme alındı',
    tlPaymentFailed: 'Ödeme başarısız',
    tlRefunded: 'Ödeme iade edildi',
    tlShipped: 'Kargoya verildi',
    tlUpdated: (status: string) => `Son güncelleme — ${status}`,
    printSlip: 'Paketleme fişi yazdır',
    slipTitle: 'Paketleme fişi',
    slipOrder: 'Sipariş no',
    slipDate: 'Tarih',
    slipShipTo: 'Teslimat adresi',
    slipItems: 'Ürünler',
    slipQty: 'Adet',
    slipVariant: 'Renk / Beden',
    slipProduct: 'Ürün',
    slipNote: 'Müşteri notu',
    slipCheck: 'Kontrol',
    notesTitle: 'Yönetici notu',
    notesHint: 'Yalnızca panelde görünür; müşteriye gönderilmez.',
    notesSave: 'Notu kaydet',
    notesSaved: 'Not kaydedildi.',
  },

  /** API bağlı modda sipariş durumları (demo/new/paid/shipped/cancelled) — yerel demo durumlarından farklıdır. */
  ordersApi: {
    statusLabels: { demo: 'Demo', new: 'Yeni', pending_payment: 'Ödeme bekleniyor', paid: 'Ödendi', shipped: 'Kargoda', cancelled: 'İptal' } as Record<string, string>,
    statusLabel: 'Durum',
    statusTitle: 'Sipariş durumu',
    newStatus: 'Yeni durum',
    changeStatus: 'Durumu güncelle',
    statusUpdated: 'Sipariş durumu güncellendi.',
    statusConfirmTitle: (from: string, to: string) => `Durum "${from}" → "${to}" olarak değişsin mi?`,
    statusConfirmText: 'Müşteri hesabında sipariş durumu güncellenir.',
    cancelConfirmTitle: 'Sipariş iptal edilsin mi?',
    cancelConfirmText: 'Sipariş iptal edilir ve ürünlerin stoğu geri yüklenir. Bu işlem müşteri hesabına yansır.',
    cancelConfirm: 'Evet, iptal et',
    reopenHint: 'İptal edilmiş siparişin durumu yalnızca sunucu izin verirse değiştirilebilir.',
    shipTitle: 'Kargo',
    carrierLabel: 'Kargo firması',
    carrierPlaceholder: 'Firma seçin',
    carrierOther: 'Diğer',
    carriers: ['Yurtiçi Kargo', 'Aras Kargo', 'MNG Kargo', 'PTT Kargo', 'Sürat Kargo', 'UPS', 'DHL', 'HepsiJET', 'Trendyol Express'] as readonly string[],
    carrierCustom: 'Firma adı',
    trackingLabel: 'Takip numarası',
    trackingRequired: 'Kargoya verildi olarak işaretlemek için takip numarası girin.',
    trackingLink: 'Kargo takibini aç',
    shippedAt: 'Kargoya veriliş',
    shipSave: 'Kargo bilgisini kaydet',
    shipSaved: 'Kargo bilgisi kaydedildi.',
    extrasUnavailable: 'Kargo firması, takip numarası ve yönetici notu için sunucu güncellemesi bekleniyor.',
    extrasDropped: 'Durum güncellendi; ancak sunucu kargo bilgisini kaydetmedi (sunucu güncellemesi bekleniyor).',
    missingFeatures: 'İade/iptal/değişim talep akışı için API uç noktası henüz yok.',
    paymentLabel: 'Ödeme',
    paymentNone: '—',
    paymentStatus: { initialized: 'Başlatıldı', success: 'Alındı', failure: 'Başarısız', refunded: 'İade edildi' } as Record<string, string>,
    paymentTitle: 'Ödeme',
    paymentId: 'Ödeme no',
    paymentProvider: 'Sağlayıcı',
    paymentInstallment: 'Taksit',
    paymentSingle: 'Tek çekim',
    paymentCard: 'Kart',
    paymentPaid: 'Tahsil edilen',
    paymentError: 'Son hata',
    paymentAttempts: (n: number) => `${n} deneme`,
    fraudReview: 'iyzico sahtecilik incelemesinde — onay gelmeden kargolamayın.',
    refund: 'Tam iade et',
    refundTitle: 'Ödeme iade edilsin mi?',
    refundConfirm: (total: string) => `${total} tutarındaki ödeme karta iade edilecek ve sipariş iptal edilecek (stok geri yüklenir). Bu işlem geri alınamaz.`,
    refundYes: 'Evet, iade et',
    refundNo: 'Vazgeç',
    refunding: 'İade ediliyor…',
    refunded: 'Ödeme iade edildi, sipariş iptal edildi.',
    statusLockedHint: "'Ödeme bekleniyor' ve 'Ödendi' durumları ödeme sağlayıcısından gelir; ödenmiş sipariş iade ile iptal edilir.",
  },

  coupons: {
    title: 'Kuponlar',
    subtitle: 'İndirim kodlarını oluşturun, sınırlarını ve geçerlilik tarihlerini yönetin.',
    feature: 'Kuponlar',
    add: 'Yeni kupon',
    empty: 'Henüz kupon yok.',
    emptyText: 'İlk kuponu oluşturarak kampanya başlatın.',
    emptyFiltered: 'Aramanızla eşleşen kupon yok.',
    searchPlaceholder: 'Kupon kodu',
    statusFilter: 'Durum',
    colCode: 'Kod',
    colType: 'Tür',
    colValue: 'Değer',
    colUsage: 'Kullanım',
    colValidity: 'Geçerlilik',
    colStatus: 'Durum',
    typePercent: 'Yüzde',
    typeFixed: 'Sabit tutar',
    statusActive: 'Aktif',
    statusInactive: 'Pasif',
    statusScheduled: 'Başlamadı',
    statusExpired: 'Süresi doldu',
    statusExhausted: 'Limit doldu',
    validityAlways: 'Süresiz',
    validityFrom: (d: string) => `${d} itibarıyla`,
    validityUntil: (d: string) => `${d} tarihine kadar`,
    validityRange: (a: string, b: string) => `${a} – ${b}`,
    usage: (used: number, limit: number | null) => (limit == null ? `${used} / sınırsız` : `${used} / ${limit}`),
    createTitle: 'Yeni kupon',
    editTitle: (code: string) => `Kupon: ${code}`,
    codeLabel: 'Kupon kodu',
    codeHint: 'Büyük harf, rakam, - ve _ (4–40 karakter). Müşteri sepette bu kodu girer.',
    codeInvalid: 'Kod 4–40 karakter olmalı; yalnızca A–Z, 0–9, - ve _ kullanılabilir.',
    typeLabel: 'İndirim türü',
    valueLabelPercent: 'İndirim oranı',
    valueLabelFixed: 'İndirim tutarı',
    valueInvalidPercent: 'Oran 1 ile 100 arasında olmalı.',
    valueInvalidFixed: 'Tutar 0’dan büyük olmalı.',
    minSubtotalLabel: 'Alt sepet tutarı',
    minSubtotalHint: 'Boş bırakılırsa alt limit yok.',
    usageLimitLabel: 'Toplam kullanım limiti',
    usageLimitHint: 'Boş = sınırsız.',
    perCustomerLabel: 'Müşteri başına limit',
    perCustomerHint: 'Boş = sınırsız.',
    startsAtLabel: 'Başlangıç tarihi',
    expiresAtLabel: 'Bitiş tarihi',
    datesInvalid: 'Bitiş tarihi başlangıçtan önce olamaz.',
    intInvalid: 'En az 1 olan bir tam sayı girin ya da boş bırakın.',
    amountInvalid: 'Geçerli bir tutar girin ya da boş bırakın.',
    activeLabel: 'Kupon aktif',
    activeHint: 'Pasif kuponlar sepette kabul edilmez.',
    rulesTitle: 'Kullanım kuralları',
    validityTitle: 'Geçerlilik',
    save: 'Kuponu kaydet',
    create: 'Kuponu oluştur',
    created: 'Kupon oluşturuldu.',
    saved: 'Kupon kaydedildi.',
    deactivate: 'Pasifleştir',
    activate: 'Etkinleştir',
    deactivated: 'Kupon pasifleştirildi.',
    activated: 'Kupon etkinleştirildi.',
    deleteTitle: (code: string) => `"${code}" silinsin mi?`,
    deleteText: 'Hiç kullanılmamış kupon kalıcı olarak silinir. Kullanılmış kupon silinmez, pasifleştirilir.',
    deleteConfirm: 'Sil',
    deleted: 'Kupon silindi.',
    deletedDeactivated: 'Kupon kullanıldığı için silinmedi, pasifleştirildi.',
    usedCount: (n: number) => `${n} kez kullanıldı`,
    createdAt: 'Oluşturulma',
  },

  customers: {
    title: 'Müşteriler',
    subtitle: 'Kayıtlı müşteriler, siparişleri ve ilk sipariş indirim hakkı.',
    feature: 'Müşteri listesi',
    empty: 'Henüz kayıtlı müşteri yok.',
    emptyFiltered: 'Aramanızla eşleşen müşteri yok.',
    searchPlaceholder: 'Ad veya e-posta',
    colName: 'Müşteri',
    colCreated: 'Kayıt',
    colOrders: 'Sipariş',
    colTotal: 'Toplam harcama',
    colDiscount: 'İlk sipariş indirimi',
    discountEligible: 'Hakkı var',
    discountUsed: 'Kullandı',
    discountNone: 'Hakkı yok',
    viewDetail: (name: string) => `${name} müşteri detayını aç`,
    detailOrders: 'Siparişleri',
    detailNoOrders: 'Bu müşterinin siparişi yok.',
    detailAddresses: 'Kayıtlı adresler',
    detailNoAddresses: 'Kayıtlı adres yok.',
    detailDefault: 'Varsayılan',
    detailSummary: 'Özet',
    lastOrder: 'Son sipariş',
    discountTitle: 'İlk sipariş indirimi',
    discountToggle: 'İndirim hakkı açık',
    discountHint: 'Kapatılırsa müşteri üyelik indiriminden yararlanamaz. Açılırsa kurala (yalnızca ilk sipariş) göre uygulanır.',
    discountSaved: (on: boolean) => (on ? 'İndirim hakkı açıldı.' : 'İndirim hakkı kapatıldı.'),
    discountConfirmOffTitle: 'İndirim hakkı kapatılsın mı?',
    discountConfirmOffText: 'Müşteri bir sonraki siparişinde üyelik indirimi alamaz.',
    openOrder: 'Siparişi aç',
  },

  content: {
    title: 'İçerik',
    subtitle: 'Mağaza metinlerini sayfa sayfa düzenleyin. Her alanın Türkçesi solda, İngilizcesi sağda.',
    brandTitle: 'Marka ve iletişim bilgileri',
    brandDesc: 'Ana sayfa koleksiyon metni, arama önerileri ve iletişim sayfası.',
    infoPagesSkipNote: '"İletişim" sayfası marka bilgileri alanlarını kullanır.',
    cookieTitle: 'Çerez metinleri',
    cookieDesc: 'Çerez bildirimi ve kategori açıklamaları.',
    cookieCategoriesTitle: 'Çerez kategorisi açıklamaları',
    productionTitle: 'Üretim',
    productionDesc: 'Ana sayfadaki üretim bölümü.',
    productionIntroLabel: 'Giriş metni',
    productionStepsTitle: 'Aşamalar',
    sizeGuideTitle: 'Beden rehberi (ürün sayfası)',
    sizeGuideDesc: 'Ürün sayfasındaki beden tablosu ve notu.',
    trHeading: 'Türkçe',
    enHeading: 'İngilizce (/en)',
    enLabel: (label: string) => `${label} — EN`,
    enPlaceholder: 'Boşsa Türkçe gösterilir',
    enNote:
      'İngilizce alanı boş bırakılırsa İngilizce sitede hazır İngilizce metin, o da yoksa Türkçe metin gösterilir. Türkçe metni değiştirdiğinizde İngilizcesini de güncelleyin.',
    viewPage: 'Sayfayı görüntüle',
    changed: 'değişti',
    changedCount: (n: number) => `${n} değişiklik`,
    expandAll: 'Tümünü aç',
    collapseAll: 'Tümünü kapat',
    filterPlaceholder: 'Sayfa veya alan ara',
    noMatch: 'Aramanızla eşleşen alan yok.',
    groupPages: 'Bilgi sayfaları',
    groupLegal: 'Hukuki metinler',
    groupSite: 'Site genelinde',
    sssHint: 'Biçim: soru satırı "S:", cevap satırı "C:" ile başlar (İngilizcede "Q:" / "A:"). Cevap birden çok satır olabilir; soruları boş satırla ayırın.',
    legalHint: 'Biçim: "## Başlık", "### Alt başlık", "**kalın**", satır başında "* " madde, "---" ayırıcı. Boş satır yeni paragraf.',
    // Canlı önizleme (grup kartındaki "Önizleme" anahtarı — ContentPreviewPane)
    preview: 'Önizleme',
    previewClose: 'Önizlemeyi kapat',
    previewTitle: 'Canlı önizleme',
    previewHint: 'Taslak metinler kaydedilmeden canlı sayfada gösterilir; değişen alanlar çerçeveyle vurgulanır.',
    previewLangLabel: 'Dil',
    previewLangTr: 'TR',
    previewLangEn: 'EN',
    previewDeviceLabel: 'Cihaz',
    previewDesktop: 'Masaüstü',
    previewTablet: 'Tablet',
    previewMobile: 'Mobil',
    previewGoToChanged: 'Değişen alana git',
    previewOpenTab: 'Yeni sekmede aç',
    previewLoading: 'Önizleme yükleniyor…',
    previewMissing: (labels: string) => `Bu sayfada görünmeyen değişiklikler: ${labels}`,
    previewNoPage: 'Bu alanlar ürün sayfasındaki Beden Rehberi çekmecesinde görünür; sayfa önizlemesi yok.',
    previewPopularNote: 'Arama panelinde görünür (önizlemede alan odaklanınca panel açılır).',
    previewPageHome: 'Ana sayfa',
    previewPageProduction: 'Ana sayfa · Üretim bölümü',
    previewPageCurrent: (path: string) => `Şu an: ${path}`,
  },

  settings: {
    title: 'Ayarlar',
    subtitle: 'Mağaza genelindeki kurallar. Değişiklikler kaydedildiğinde mağazaya yansır.',
    brandTitle: 'Marka',
    brandDesc: 'Başlıkta, e-postalarda ve sayfa başlıklarında kullanılan ad.',
    brandNameLabel: 'Marka adı',
    brandShortNameLabel: 'Kısa ad',
    brandShortNameHint: 'Dar alanlarda (mobil başlık, e-posta konusu) kullanılır.',
    shippingTitle: 'Kargo',
    shippingDesc: 'Sepette ve ödeme adımında gösterilen kargo ücreti.',
    shippingAmountLabel: 'Kargo ücreti',
    shippingAmountHint: 'Boş bırakılırsa mağazada "belirlenecek" yazar.',
    freeOverLabel: 'Ücretsiz kargo eşiği',
    freeOverHint: 'Sepet ara toplamı bu tutar ve üzerindeyse kargo ücretsiz olur. Boş = eşik yok.',
    discountTitle: 'Üyelik indirimi',
    discountDesc: 'Hesap açan müşteriye uygulanan kampanya.',
    discountEnabledLabel: 'Üyelik indirimi aktif',
    discountPercentLabel: 'İndirim oranı',
    discountModeLabel: 'Uygulama şekli',
    discountModeAutomatic: 'Otomatik (hesap açınca)',
    discountModeCode: 'Kod ile',
    discountCodeLabel: 'İndirim kodu',
    discountCodeHint: 'Yalnızca "Kod ile" seçiliyken kullanılır.',
    discountMinSubtotalLabel: 'Minimum sepet tutarı',
    discountUsageLimitLabel: 'Kullanım sınırı',
    discountExpiresAtLabel: 'Son kullanım tarihi',
    emptyMeansNone: 'Boş = tanımsız.',
    discountFirstOrderOnlyLabel: 'Yalnızca ilk siparişte',
    discountFirstOrderOnlyHint: 'İptal edilen sipariş sayılmaz; ilk sipariş iptal edilirse hak geri gelir.',
    inventoryTitle: 'Stok ve "Yeni" rozeti',
    inventoryDesc: 'Düşük stok uyarısı ve otomatik rozet kuralı.',
    lowStockThresholdLabel: 'Düşük stok eşiği',
    lowStockThresholdHint: 'Stoğu 1 ile bu sayı arasındaki varyantlar "düşük stok" sayılır; ürün sayfasında "Son N adet" notu çıkar.',
    newBadgeDaysLabel: '"Yeni" rozeti süresi',
    newBadgeDaysHint: 'Otomatik rozetli ürünler oluşturulduktan sonra bu kadar gün "Yeni" görünür.',
    inventoryInvalid: 'Düşük stok eşiği 0–9999, gün sayısı 0–3650 arasında tam sayı olmalı.',
    paymentTitle: 'Ödeme ve taksit',
    paymentDesc: 'Çevrim içi ödeme sağlayıcısı sunucu ortamından gelir; taksit seçenekleri buradan ayarlanır.',
    paymentProvider: 'Ödeme sağlayıcısı',
    providerNames: { none: 'Kapalı (tahsilatsız)', iyzico: 'iyzico', fake: 'Test (fake)' } as Record<string, string>,
    installmentsLabel: 'Taksit seçenekleri',
    installmentsDefault: 'Sunucu varsayılanını kullan',
    installmentsDefaultHint: 'Ortam değişkenindeki (PAYMENT_INSTALLMENTS) seçenekler geçerli olur.',
    installmentsCustom: 'Seçenekleri belirle',
    installmentOption: (n: number) => (n === 1 ? 'Tek çekim' : `${n} taksit`),
    installmentsInvalid: 'En az bir taksit seçeneği seçin.',
    installmentsHint: 'Seçenekler iyzico ödeme sayfasında sunulur; vade farkı iyzico ayarlarınıza göre uygulanır.',
    supportTitle: 'Destek ve sosyal medya',
    supportDesc: 'Mağazadaki iletişim ve sosyal medya bağlantıları. Boş bırakılan alan mağazada gösterilmez.',
    whatsappLabel: 'WhatsApp numarası',
    whatsappHint: 'Uluslararası biçimde, ör. 905xxxxxxxxx.',
    emailLabel: 'Destek e-postası',
    emailInvalid: 'Geçerli bir e-posta adresi girin.',
    instagramLabel: 'Instagram',
    tiktokLabel: 'TikTok',
    pinterestLabel: 'Pinterest',
    socialHint: 'Tam bağlantı, ör. https://instagram.com/…',
    offerTitle: 'Teklif paneli',
    offerDesc: 'Çerez kararından sonra gösterilen üyelik teklifi.',
    offerDelayLabel: 'Gösterim gecikmesi',
    offerDelayHint: 'Milisaniye (6000 = 6 saniye).',
    numberInvalid: 'Geçerli bir sayı girin ya da boş bırakın.',
    percentInvalid: 'Oran 0 ile 100 arasında olmalı.',
    mediaLabels: {
      heroDesktop: 'Açılış görseli (masaüstü)',
      heroMobile: 'Açılış görseli (mobil)',
      collection: 'Koleksiyon tanıtım görseli',
      auth: 'Giriş / kayıt görseli',
      logo: 'Logo',
      productionVideo: 'Üretim videosu',
      productionVideoPoster: 'Üretim videosu kapak görseli',
      productionCutting: 'Kumaş kesim aşaması',
      productionSewing: 'Dikim aşaması',
      productionQuality: 'Kalite kontrol',
    },
  },

  mediaPage: {
    title: 'Görseller',
    subtitle: 'Mağazanın marka görselleri. Yüklediğiniz görsel mağazada hemen kullanılır.',
    hint: 'Görseli yuvaya sürükleyip bırakın ya da tıklayıp seçin. JPG, PNG, WebP, AVIF (video: MP4, WebM); en fazla 15 MB. SVG güvenlik nedeniyle sunucuda kabul edilmez.',
    groupHero: 'Açılış',
    groupHeroDesc: 'Ana sayfanın en üstündeki büyük görsel. Masaüstü ve mobil için ayrı kırpım yükleyin.',
    groupBrand: 'Koleksiyon, giriş ve logo',
    groupBrandDesc: 'Ana sayfa koleksiyon tanıtımı, giriş/kayıt sayfası ve başlıktaki logo.',
    groupProduction: 'Üretim aşamaları',
    groupProductionDesc: 'Ana sayfadaki üretim bölümü: video, kapak ve üç aşama görseli.',
    saved: (label: string) => `${label} kaydedildi.`,
    removed: (label: string) => `${label} kaldırıldı.`,
    removeTitle: (label: string) => `${label} kaldırılsın mı?`,
    removeText: 'Mağazada bu alan boş yer tutucu olarak görünür.',
    removeTextDefault: 'Yüklenen görsel kaldırılır; mağaza pakette gelen varsayılan görsele döner.',
    removeConfirm: 'Kaldır',
    ratio: (r: string) => `Önerilen oran ${r}`,
    localSaved: 'Kaydedildi — mağazada görmek için sayfayı yenileyin.',
    badgeUploaded: 'Yüklenen',
    badgeDefault: 'Varsayılan (sitede görünen)',
    viewInStore: 'Mağazada gör',
    defaultHint: 'Boş yuvalarda mağaza pakette gelen varsayılan görseli gösterir; bir dosya yüklerseniz onun yerine geçer. "Kaldır" yalnızca yüklenen görseller için geçerlidir.',
  },

  users: {
    title: 'Kullanıcılar',
    subtitle: 'Panele erişebilen yönetici hesapları.',
    empty: 'Henüz yönetici kullanıcı yok.',
    username: 'Kullanıcı adı',
    role: 'Rol',
    status: 'Durum',
    roleOwner: 'Sahip (owner)',
    roleEditor: 'Editör',
    roleHelp: 'Sahip: tüm yetkiler (kullanıcı ve veri yönetimi dahil). Editör: ürün, içerik, sipariş, ayar.',
    active: 'Aktif',
    inactive: 'Pasif',
    lastLogin: 'Son giriş',
    created: 'Oluşturulma',
    never: 'Hiç',
    you: 'siz',
    add: 'Yeni kullanıcı',
    createTitle: 'Yeni kullanıcı',
    usernameLabel: 'Kullanıcı adı',
    usernameHint: 'En az 3 karakter.',
    usernameInvalid: 'Kullanıcı adı en az 3 karakter olmalı.',
    passwordLabel: 'Parola',
    passwordHint: 'En az 8 karakter.',
    passwordInvalid: 'Parola en az 8 karakter olmalı.',
    roleLabel: 'Rol',
    createButton: 'Kullanıcı ekle',
    createdToast: (u: string) => `${u} eklendi.`,
    changePassword: 'Parola değiştir',
    changePasswordTitle: (u: string) => `${u} — yeni parola`,
    newPasswordLabel: 'Yeni parola',
    changePasswordButton: 'Parolayı güncelle',
    passwordChanged: 'Parola güncellendi.',
    deactivate: 'Pasifleştir',
    activate: 'Etkinleştir',
    deactivateTitle: (u: string) => `${u} pasifleştirilsin mi?`,
    deactivateText: 'Bu kullanıcı panele giriş yapamaz. İstediğiniz zaman yeniden etkinleştirebilirsiniz.',
    activated: (u: string) => `${u} etkinleştirildi.`,
    deactivated: (u: string) => `${u} pasifleştirildi.`,
    ownerOnlyNote: 'Kullanıcı ekleme ve düzenleme yalnızca hesap sahibi (owner) tarafından yapılabilir.',
  },

  data: {
    title: 'Veri',
    subtitle: 'Katalog, içerik ve ayarları yedekleyin ya da yedekten geri yükleyin.',
    exportTitle: 'Dışa aktar',
    exportDesc: 'Ürün katalogu, içerik alanları, ayarlar ve marka görseli bağlantıları tek bir JSON dosyasına indirilir. Kullanıcılar, müşteriler ve siparişler kapsam dışıdır.',
    exportHint: 'Tüm yerel değişiklikleri ve yüklenen görselleri tek bir dosyada indirin.',
    exportButton: 'JSON olarak indir',
    exported: 'Yedek indirildi.',
    importTitle: 'İçe aktar',
    importDesc: 'Yalnızca bu sayfadan indirilmiş bir dosya (teshvikiye-api-export) yüklenebilir. İçe aktarma ürün katalogunu, içeriği ve ayarları TAMAMEN DEĞİŞTİRİR.',
    importHint: 'Daha önce dışa aktarılmış bir dosyayı yükleyerek yerel verileri geri getirin.',
    importButton: 'Dosya seç',
    importConfirmTitle: 'Veriler değiştirilsin mi?',
    importConfirmText: (name: string) => `"${name}" içe aktarılacak. Mevcut katalog, içerik ve ayarlar bu dosyadakilerle değiştirilir. Bu işlem geri alınamaz — önce dışa aktararak yedek almanız önerilir.`,
    importConfirm: 'İçe aktar',
    importSuccess: (mediaCount: number) => `İçe aktarıldı — ${mediaCount} görsel dahil.`,
    importDone: 'İçe aktarıldı.',
    importError: (message: string) => `İçe aktarma başarısız: ${message}`,
    invalidJson: 'Geçersiz JSON dosyası.',
    wrongFormat: 'Bu dosya API dışa aktarma biçiminde değil (yerel panel dışa aktarımı burada kullanılamaz).',
    resetTitle: 'Yerel değişiklikleri sıfırla',
    resetHint: 'Tüm ürün, içerik ve ayar değişiklikleri ile yüklenen görseller kalıcı olarak silinir. Bu işlem geri alınamaz.',
    resetButton: 'Tümünü sıfırla',
    resetConfirmTitle: 'Tüm yerel değişiklikler silinsin mi?',
    resetConfirmYes: 'Evet, sıfırla',
    resetDone: 'Sıfırlandı — mağazada görmek için sayfayı yenileyin.',
    ownerOnly: 'İçe aktarma yalnızca hesap sahibi (owner) tarafından yapılabilir.',
  },

  /** `/admin/analitik` — birinci taraf ziyaret/davranış/satış analitiği (bkz. adminApi.ts → AnalyticsOverview). */
  analytics: {
    title: 'Analitik',
    subtitle: 'Ziyaret, davranış ve satış ölçümleri. Veriler yalnızca bu mağazada toplanır; IP ve ham tarayıcı bilgisi saklanmaz.',
    feature: 'Analitik',
    rangeLabel: 'Aralık',
    ranges: { '7d': '7 gün', '30d': '30 gün', '90d': '90 gün', '12m': '12 ay' } as Record<string, string>,
    periodNote: (from: string, to: string, days: number) => `${from} – ${to} · ${days} gün`,
    localOnlyTitle: 'Analitik yalnızca API modunda',
    localOnlyText: 'Ziyaret ve satış ölçümü sunucudan okunur; yerel demo modunda gösterilecek veri yok.',
    noDataTitle: 'Veri toplanmaya başlandı',
    noDataText: 'İlk ziyaretlerle birlikte burada görünecek. Sayfa görüntülemeleri herkes için, ziyaretçi ve oturum sayıları yalnızca analitik çerezlerini kabul edenler için sayılır.',
    staleNote: 'Veriler yenileniyor…',
    dataTable: 'Veri tablosu',
    empty: 'Bu aralıkta veri yok.',
    footer: (generatedAt: string, retention: number, since: string) => `Son güncelleme: ${generatedAt} · Saklama: ${retention} gün · İlk kayıt: ${since}`,
    eventsInRange: (n: number) => `${tl(n)} olay`,

    kpi: {
      pageviews: 'Sayfa görüntüleme',
      visits: 'Ziyaret',
      visitors: 'Ziyaretçi',
      sessions: 'Oturum',
      orders: 'Sipariş',
      revenue: 'Ciro',
      conversion: 'Dönüşüm',
      aov: 'Ortalama sepet',
      consentedOnly: 'yalnızca onaylı',
      everyone: 'herkes',
      conversionSub: 'sipariş / ziyaret',
      aovSub: 'sipariş başına',
      deltaUp: (pct: string) => `▲ ${pct}`,
      deltaDown: (pct: string) => `▼ ${pct}`,
      deltaFlat: '— değişmedi',
      deltaNone: '— önceki dönem yok',
      deltaAria: (pct: string, up: boolean) => `önceki döneme göre ${up ? 'artış' : 'azalış'} ${pct}`,
    },

    traffic: {
      title: 'Ziyaret ve görüntülemeler',
      desc: 'Günlük sayfa görüntüleme, ziyaret (tam sayfa yüklemesi) ve onaylı ziyaretçi sayısı.',
      ordersTitle: 'Sipariş ve ciro',
      ordersDesc: 'Yeni, ödendi ve kargoda siparişler; iptal, ödeme bekleyen ve demo hariç.',
      revenueChart: 'Ciro',
      ordersChart: 'Sipariş sayısı',
      bucketDaily: 'günlük',
      bucketWeekly: 'haftalık toplam',
      bucketMonthly: 'aylık toplam',
      weekOf: (d: string) => `${d} haftası`,
    },

    funnel: {
      title: 'Dönüşüm hunisi',
      desc: 'Ziyaretten siparişe adımlar ve adımlar arası dönüşüm.',
      steps: { pageview: 'Sayfa görüntüleme', productView: 'Ürün görüntüleme', addToCart: 'Sepete ekleme', checkout: 'Ödeme başlangıcı', order: 'Sipariş' } as Record<string, string>,
      basisSessions: 'Oturum bazlı — her adım, o adımı en az bir kez yapan onaylı oturum sayısıdır.',
      basisEvents: 'Olay bazlı — analitik onayı veren ziyaretçi henüz yok; adımlar olay sayılarıdır.',
      overall: (pct: string) => `Toplam dönüşüm ${pct}`,
      stepRate: (pct: string) => `${pct} geçti`,
    },

    sources: {
      title: 'Ziyaret kaynakları',
      desc: 'Ziyaretin ilk sayfasındaki yönlendiren site, kampanya etiketi (utm) ve dil.',
      referrers: 'Yönlendirenler',
      direct: 'Doğrudan / yazarak',
      campaigns: 'Kampanyalar',
      noCampaigns: 'Kampanya etiketli (utm) ziyaret yok.',
      noReferrers: 'Yönlendiren kaydı yok.',
      locales: 'Dil payı',
      visitsUnit: (n: number) => `${tl(n)} ziyaret`,
    },

    devices: {
      title: 'Cihaz ve tarayıcı',
      desc: 'Sayfa görüntülemelerine göre cihaz sınıfı, tarayıcı ve işletim sistemi.',
      devices: 'Cihaz',
      browsers: 'Tarayıcı',
      os: 'İşletim sistemi',
      viewsUnit: (n: number) => `${tl(n)} görüntüleme`,
    },

    time: {
      title: 'Zaman',
      desc: 'Sayfa görüntülemelerinin gün ve saate dağılımı (İstanbul saati).',
      heatmap: 'Saat × gün',
      weekdays: 'Haftanın günleri',
      weekdayShort: ['Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz'] as readonly string[],
      weekdayLong: ['Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi', 'Pazar'] as readonly string[],
      hourRange: (h: number) => `${String(h).padStart(2, '0')}:00–${String((h + 1) % 24).padStart(2, '0')}:00`,
      less: 'Az',
      more: 'Çok',
    },

    content: {
      title: 'İçerik',
      desc: 'En çok görüntülenen sayfalar, ürün performansı ve mağaza içi aramalar.',
      pages: 'En çok görüntülenen sayfalar',
      pageHome: 'Ana sayfa',
      pageCollection: 'Koleksiyon',
      pageProduct: 'Ürün',
      pageInfo: 'Bilgi',
      pageNames: {
        '/sepet': 'Sepet',
        '/odeme': 'Ödeme',
        '/giris': 'Giriş',
        '/kayit': 'Kayıt',
        '/hesap': 'Hesap',
        '/favoriler': 'Favoriler',
        '/arama': 'Arama',
        '/sifre-sifirla': 'Şifre sıfırlama',
        '/hesap/dogrula': 'E-posta doğrulama',
      } as Record<string, string>,
      pageCheckoutResult: 'Ödeme sonucu',
      visitorsUnit: (n: number) => `${tl(n)} ziyaretçi`,
      products: 'Ürünler',
      colProduct: 'Ürün',
      colViews: 'Görüntülenme',
      colAddToCart: 'Sepete ekleme',
      colAddRate: 'Sepet oranı',
      colOrdered: 'Satılan',
      colRevenue: 'Ciro',
      openProduct: (name: string) => `${name} ürününü aç`,
      noProducts: 'Ürün görüntülemesi yok.',
      searches: 'Aramalar',
      noSearches: 'Arama kaydı yok.',
      searchUnit: (n: number) => `${tl(n)} arama`,
      zeroResults: (n: number) => `${tl(n)} sonuçsuz`,
    },

    sales: {
      title: 'Satış',
      desc: 'Aralıkta oluşturulan siparişler (demo hariç) — tüm durumlar.',
      byStatus: 'Durum dağılımı',
      memberOrders: 'Üye siparişi',
      guestOrders: 'Misafir siparişi',
      couponOrders: 'Kuponlu',
      firstOrderDiscountOrders: 'İlk sipariş indirimli',
      topCoupons: 'En çok kullanılan kuponlar',
      noCoupons: 'Kupon kullanımı yok.',
      couponDiscount: (amount: string) => `${amount} indirim`,
      byCity: 'Şehirler',
      noCities: 'Şehir bilgisi yok.',
      byHour: 'Sipariş saatleri',
      byLocale: 'Sipariş dili',
      ordersUnit: (n: number) => `${tl(n)} sipariş`,
    },

    customers: {
      title: 'Müşteriler',
      desc: 'Yeni üyelikler ve alıcı davranışı.',
      newSeries: 'Yeni üyeler',
      total: 'Toplam üye',
      newInRange: 'Aralıkta yeni',
      buyersInRange: 'Alıcı',
      buyersSub: 'aralıkta sipariş veren',
      repeatBuyers: 'Tekrar alıcı',
      repeatSub: '2+ sipariş',
    },

    consent: {
      title: 'Çerez onayı',
      desc: 'Çerez bildirimindeki kararlar ve analitik çerezlerinin kabul oranı.',
      decisions: 'Kararlar',
      acceptAll: 'Hepsini kabul',
      necessaryOnly: 'Yalnızca gerekli',
      custom: 'Özel seçim',
      optIn: 'Analitik kabul oranı',
      optInSub: (n: number, total: number) => `${tl(n)} / ${tl(total)} karar`,
      consentedShare: (pct: string) => `Sayfa görüntülemelerinin ${pct} kadarı analitik onaylı ziyaretçilerden geldi.`,
      note: 'Ziyaretçi ve oturum sayıları yalnızca analitik çerezlerini kabul edenleri kapsar; sayfa görüntülemeleri ve ziyaretler herkesi kapsar.',
      noDecisions: 'Henüz çerez kararı yok.',
    },
  },

  media: {
    upload: 'Yükle',
    replace: 'Değiştir',
    remove: 'Kaldır',
    dropHint: 'Sürükleyip bırakın ya da tıklayın',
    uploadAria: (label: string) => `${label} yükle`,
    replaceAria: (label: string) => `${label} — değiştirmek için tıklayın`,
    typeImage: 'Desteklenmeyen dosya türü. JPG, PNG, WebP veya AVIF yükleyin (SVG kabul edilmez).',
    typeVideo: 'Desteklenmeyen dosya türü. MP4 veya WebM yükleyin.',
    tooLarge: (mb: number) => `Dosya çok büyük (${mb.toLocaleString('tr-TR')} MB). En fazla 15 MB yüklenebilir.`,
    largeFile: "Dosya 2 MB'tan büyük — yine de yüklenebilir.",
  },
} as const
